### ISSUE TITLE
managed db

### ISSUE THREAD

**Issue by DevOpsJake** [XITASO/atlassian-confluence-formula#1]
Hi Tobias,

Amazing confluence formula you put together! Just wondering if you will be adding functionality to pass managed DB parameters similar to your JIRA formula :)

Thanks,
Jake

**Comment by corux** [comment]
Hello Jake,
I'm currently not planning to introduce management of database parameters. If you'd be willing to extend the formula, I'd be happy to accept pull requests!

For some background info: most Atlassian tools (including Confluence) cannot be pre-configured before installation and have to be configured in the setup wizard. Therefore the use-case of managing the connection string is rather limited to e.g. updating the credentials for existing installations.

Regards, Tobias

**Comment by DevOpsJake** [comment]
I tried working toward a solution and see what you mean about the issues around attempting to pre-configure. If I do come up with something I'll be sure to submit a PR!

Thanks for the response.
